services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: iam
    ports:
      - "5432:5432"

  imss-service:
    container_name: imss-service
    build:
      context: ./packages/tokens-service
      dockerfile: Dockerfile
    ports:
      - "80:80"

  token-service:
    image: node:20
    container_name: token-service
    working_dir: /app
    volumes:
      - ./packages/tokens-service:/app
    command: sh -c "npm install && npm run start:dev"
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@postgres:5432/iam
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
